In [38]:
# x-axis: confidence
# y-aixs: coverage
# color: TP/FP
import pandas as pd

In [39]:
all_variant_calls_probeset_reports = pd.read_csv("all_variant_calls_probeset_reports_of_pandora_nanopore_no_denovo_100x.tsv", sep="\t")
all_variant_calls_probeset_reports

,sample,query_probe_header,ref_probe_header,classification
0,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=8;INTE...,>CHROM=ENA|CP039404|CP039404.1;,1.000000
1,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=21;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.000000
2,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=43;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.000000
3,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=58;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.000000
4,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=76;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.000000
...,...,...,...,...
806941,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=131;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.000000
806942,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=159;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,0.888889
806943,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=189;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.000000
806944,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=214;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.000000
806945,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=282;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,0.909091

In [40]:
classification_df_with_gene_length = pd.read_csv("classification_df_with_gene_length.csv")
classification_df_with_gene_length

,gene_name,063_STEC_classification,CFT073_classification,H131800734_classification,ST38_classification,gene_length,gene_length_category
0,GC00006917,TN,TN,TN,TP,489,500
1,Cluster_6872,TN,TN,TN,TP,157,200
2,GC00000927_2,TN,TN,TN,TP,249,300
3,Cluster_808,TN,TN,TN,TP,428,500
4,GC00008595,TN,TN,TN,TP,273,300
...,...,...,...,...,...,...,...
10427,Cluster_6971,TN,TN,TN,FN,155,200
10428,GC00004416,FN,TN,TN,TN,453,500
10429,GC00003424_1,TN,TN,TN,FN,393,400
10430,Cluster_2012,FN,TN,TN,TN,344,400
10431,GC00001036_3,TN,TN,TN,TN,747,800

In [41]:
def extract_value_from_query_probe_header(query_probe_header, field, return_type):
    string_with_field = query_probe_header[query_probe_header.index(f"{field}=") + (len(field)+1):]
    value = string_with_field[:string_with_field.index(";")]
    return return_type(value)

all_variant_calls_probeset_reports["gene_name"] = all_variant_calls_probeset_reports["query_probe_header"].apply(
extract_value_from_query_probe_header, field=">CHROM", return_type=str)
all_variant_calls_probeset_reports["SVTYPE"] = all_variant_calls_probeset_reports["query_probe_header"].apply(
extract_value_from_query_probe_header, field="SVTYPE", return_type=str)
all_variant_calls_probeset_reports["GT_CONF"] = all_variant_calls_probeset_reports["query_probe_header"].apply(
extract_value_from_query_probe_header, field="GT_CONF", return_type=float)
all_variant_calls_probeset_reports

,sample,query_probe_header,ref_probe_header,classification,gene_name,SVTYPE,GT_CONF
0,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=8;INTE...,>CHROM=ENA|CP039404|CP039404.1;,1.000000,GC00000161_7,SNP,248.257004
1,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=21;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.000000,GC00000161_7,PH_SNPs,130.634995
2,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=43;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.000000,GC00000161_7,SNP,96.819801
3,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=58;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.000000,GC00000161_7,SNP,195.996994
4,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=76;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.000000,GC00000161_7,SNP,229.673004
...,...,...,...,...,...,...,...
806941,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=131;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.000000,Cluster_1463,SNP,81.844597
806942,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=159;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,0.888889,Cluster_1463,PH_SNPs,28.294001
806943,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=189;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.000000,Cluster_1463,SNP,81.844597
806944,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=214;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.000000,Cluster_1463,PH_SNPs,56.518398
806945,ST38,>CHROM=Cluster_1463;SAMPLE=ST38;POS=282;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,0.909091,Cluster_1463,INDEL,121.936996

In [42]:
all_variant_calls_probeset_reports_with_gene_classification = \
all_variant_calls_probeset_reports.merge(classification_df_with_gene_length, on="gene_name", how="inner")
all_variant_calls_probeset_reports_with_gene_classification

,sample,query_probe_header,ref_probe_header,classification,gene_name,SVTYPE,GT_CONF,063_STEC_classification,CFT073_classification,H131800734_classification,ST38_classification,gene_length,gene_length_category
0,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=8;INTE...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,SNP,248.257004,TP,TP,TN,TP,978,1000
1,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=21;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,PH_SNPs,130.634995,TP,TP,TN,TP,978,1000
2,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=43;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,SNP,96.819801,TP,TP,TN,TP,978,1000
3,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=58;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,SNP,195.996994,TP,TP,TN,TP,978,1000
4,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=76;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,SNP,229.673004,TP,TP,TN,TP,978,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
806941,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=83;INTERVA...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.0,GC00003655_4,SNP,168.794998,TN,TN,TN,TP,150,200
806942,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=94;INTERVA...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.0,GC00003655_4,SNP,191.009995,TN,TN,TN,TP,150,200
806943,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=104;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.0,GC00003655_4,PH_SNPs,196.177002,TN,TN,TN,TP,150,200
806944,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=144;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,0.0,GC00003655_4,PH_SNPs,173.998001,TN,TN,TN,TP,150,200
806945,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=121;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.0,GC00003655_4,PH_SNPs,223.852005,TN,TN,TN,TP,150,200

In [43]:
def get_gene_classification(row):
    sample=row["sample"]
    return row[f"{sample}_classification"]

all_variant_calls_probeset_reports_with_gene_classification["gene_classification"] = \
all_variant_calls_probeset_reports_with_gene_classification.apply(get_gene_classification, axis=1)
all_variant_calls_probeset_reports_with_gene_classification

,sample,query_probe_header,ref_probe_header,classification,gene_name,SVTYPE,GT_CONF,063_STEC_classification,CFT073_classification,H131800734_classification,ST38_classification,gene_length,gene_length_category,gene_classification
0,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=8;INTE...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,SNP,248.257004,TP,TP,TN,TP,978,1000,TP
1,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=21;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,PH_SNPs,130.634995,TP,TP,TN,TP,978,1000,TP
2,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=43;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,SNP,96.819801,TP,TP,TN,TP,978,1000,TP
3,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=58;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,SNP,195.996994,TP,TP,TN,TP,978,1000,TP
4,063_STEC,>CHROM=GC00000161_7;SAMPLE=063_STEC;POS=76;INT...,>CHROM=ENA|CP039404|CP039404.1;,1.0,GC00000161_7,SNP,229.673004,TP,TP,TN,TP,978,1000,TP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
806941,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=83;INTERVA...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.0,GC00003655_4,SNP,168.794998,TN,TN,TN,TP,150,200,TP
806942,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=94;INTERVA...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.0,GC00003655_4,SNP,191.009995,TN,TN,TN,TP,150,200,TP
806943,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=104;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.0,GC00003655_4,PH_SNPs,196.177002,TN,TN,TN,TP,150,200,TP
806944,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=144;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,0.0,GC00003655_4,PH_SNPs,173.998001,TN,TN,TN,TP,150,200,TP
806945,ST38,>CHROM=GC00003655_4;SAMPLE=ST38;POS=121;INTERV...,>CHROM=ENA|CP026723|CP026723.1|pilon|pilon|pil...,1.0,GC00003655_4,PH_SNPs,223.852005,TN,TN,TN,TP,150,200,TP

In [44]:
cleaned_df = all_variant_calls_probeset_reports_with_gene_classification[[
    "gene_name",
    "sample",
    "classification",
    "SVTYPE",
    "GT_CONF",
    "gene_classification"
]]
cleaned_df

,gene_name,sample,classification,SVTYPE,GT_CONF,gene_classification
0,GC00000161_7,063_STEC,1.0,SNP,248.257004,TP
1,GC00000161_7,063_STEC,1.0,PH_SNPs,130.634995,TP
2,GC00000161_7,063_STEC,1.0,SNP,96.819801,TP
3,GC00000161_7,063_STEC,1.0,SNP,195.996994,TP
4,GC00000161_7,063_STEC,1.0,SNP,229.673004,TP
...,...,...,...,...,...,...
806941,GC00003655_4,ST38,1.0,SNP,168.794998,TP
806942,GC00003655_4,ST38,1.0,SNP,191.009995,TP
806943,GC00003655_4,ST38,1.0,PH_SNPs,196.177002,TP
806944,GC00003655_4,ST38,0.0,PH_SNPs,173.998001,TP
806945,GC00003655_4,ST38,1.0,PH_SNPs,223.852005,TP

In [ ]:
import plotly.express as px
fig = px.scatter(cleaned_df, x="GT_CONF", y="classification")
fig